(function() {
    'use strict';

    angular.module('app.generator', ['tubular.services'])
        // This Factory and the pluker button is based on Angular Documentation
        .factory('formPostData', [
            '$document', function($document) {
                return function(url, newWindow, fields) {
                    /**
                     * If the form posts to target="_blank", pop-up blockers can cause it not to work.
                     * If a user choses to bypass pop-up blocker one time and click the link, they will arrive at
                     * a new default plnkr, not a plnkr with the desired template.  Given this undesired behavior,
                     * some may still want to open the plnk in a new window by opting-in via ctrl+click.  The
                     */

                    var target = newWindow ? '_blank' : '_self';
                    var form = angular.element('<form style="display: none;" method="post" action="' + url + '" target="' + target + '"></form>');
                    angular.forEach(fields, function(value, name) {
                        var input = angular.element('<input type="hidden" name="' + name + '">');
                        input.attr('value', value);
                        form.append(input);
                    });
                    $document.find('body').append(form);
                    form[0].submit();
                    form.remove();
                };
            }
        ]).service('tubularGenerator', [
            'tubularTemplateService', 'formPostData', function tubularGenerator(tubularTemplateService, formPostData) {
                var me = this;

                me.DefaultJs = "angular.module('app', ['ngRoute','ngCookies','tubular.directives']).config(['$routeProvider', function($routeProvider) {$routeProvider.when('/', {templateUrl: 'grid.html',}).otherwise({redirectTo: '/'}); } ]);";
                me.DefaultReadme = '#Tubular WebApp\r\nYou can add your content now. Create more views @ [Tubular](http://unosquare.github.io/tubular)';

                me.createColumns = function(model, scope) {
                    scope.columns = tubularTemplateService.createColumns(model);
                };

                me.runGridTemplate = function(scope) {
                    var topToolbar = '';
                    var bottomToolbar = '';

                    if (scope.uiOptions.Pager) {
                        topToolbar += '\r\n\t<tb-grid-pager class="col-md-6"></tb-grid-pager>';
                        bottomToolbar += '\r\n\t<tb-grid-pager class="col-md-6"></tb-grid-pager>';
                    }

                    if (scope.uiOptions.ExportCsv) {
                        topToolbar += '\r\n\t<div class="col-md-3">' +
                            '\r\n\t\t<div class="btn-group">' +
                            '\r\n\t\t<tb-print-button title="Tubular" class="btn-sm"></tb-print-button>' +
                            '\r\n\t\t<tb-export-button filename="tubular.csv" css="btn-sm"></tb-export-button>' +
                            '\r\n\t\t</div>' +
                            '\r\n\t</div>';
                    }

                    if (scope.uiOptions.FreeTextSearch) {
                        topToolbar += '\r\n\t<tb-text-search class="col-md-3" css="input-sm"></tb-text-search>';
                    }

                    if (scope.uiOptions.PageSizeSelector) {
                        bottomToolbar += '\r\n\t<tb-page-size-selector class="col-md-3" selectorcss="input-sm"></tb-page-size-selector>';
                    }

                    if (scope.uiOptions.PagerInfo) {
                        bottomToolbar += '\r\n\t<tb-grid-pager-info class="col-md-3"></tb-grid-pager-info>';
                    }

                    return '<h1>Autogenerated Grid</h1>' +
                        '\r\n<div class="container">' +
                        '\r\n<tb-grid server-url="' + scope.dataUrl + '" request-method="GET" class="row" require-authentication="false" page-size="10"' +
                        (scope.isOData ? ' service-name="odata"' : '') +
                        (scope.uiOptions.Mode != 'Read-Only' ? ' editor-mode="' + scope.uiOptions.Mode.toLowerCase() + '"' : '') + '>' +
                        (topToolbar === '' ? '' : '\r\n\t<div class="row">' + topToolbar + '\r\n\t</div>') +
                        '\r\n\t<div class="row">' +
                        '\r\n\t<div class="col-md-12">' +
                        '\r\n\t<div class="panel panel-default panel-rounded">' +
                        '\r\n\t<tb-grid-table class="table-bordered">' +
                        '\r\n\t<tb-column-definitions>' +
                        (scope.uiOptions.Mode != 'Read-Only' ? '\r\n\t\t<tb-column label="Actions"><tb-column-header>{{label}}</tb-column-header></tb-column>' : '') +
                        scope.columns.map(function(el) {
                            return '\r\n\t\t<tb-column name="' + el.Name + '" label="' + el.Label + '" column-type="' + el.DataType + '" sortable="' + el.Sortable + '" ' +
                                '\r\n\t\t\tsort-order="' + el.SortOrder + '" is-key="' + el.IsKey + '" searchable="' + el.Searchable + '" visible="' + el.Visible + '">' +
                                (el.Filter ? '<tb-column-filter></tb-column-filter>' : '') +
                                '\r\n\t\t\t<tb-column-header>{{label}}</tb-column-header>' +
                                '\r\n\t\t</tb-column>';
                        }).join('') +
                        '\r\n\t</tb-column-definitions>' +
                        '\r\n\t<tb-row-set>' +
                        '\r\n\t<tb-row-template ng-repeat="row in $component.rows" row-model="row">' +
                        (scope.uiOptions.Mode != 'Read-Only' ? '\r\n\t\t<tb-cell-template>' +
                            (scope.uiOptions.Mode == 'Inline' ? '\r\n\t\t\t<tb-save-button model="row"></tb-save-button>' : '') +
                            '\r\n\t\t\t<tb-edit-button model="row"></tb-edit-button>' +
                            '\r\n\t\t</tb-cell-template>' : '') +
                        scope.columns.map(function(el) {
                            var editorTag = el.EditorType.replace(/([A-Z])/g, function($1) { return "-" + $1.toLowerCase(); });

                            return '\r\n\t\t<tb-cell-template column-name="' + el.Name + '">' +
                                (scope.uiOptions.Mode == 'Inline' ?
                                    '<' + editorTag + ' is-editing="row.$isEditing" value="row.' + el.Name + '"></' + editorTag + '>' :
                                    '\r\n\t\t\t' + el.Template) +
                                '\r\n\t\t</tb-cell-template>';
                        }).join('') +
                        '\r\n\t</tb-row-template>' +
                        '\r\n\t</tb-row-set>' +
                        '\r\n\t</tb-grid-table>' +
                        '\r\n\t</div>' +
                        '\r\n\t</div>' +
                        '\r\n\t</div>' +
                        (bottomToolbar === '' ? '' : '\r\n\t<div class="row">' + bottomToolbar + '\r\n\t</div>') +
                        '\r\n\t</div>' +
                        '\r\n</tb-grid>' +
                        '\r\n</div>';
                };

                me.runFormTemplate = function(scope) {
                    return '<h1>Autogenerated Form</h1>' +
                        '\r\n<tb-form server-url="' + scope.dataUrl + '" server-save-url="' + scope.dataUrl + '"' +
                        (scope.isOData ? ' service-name="odata"' : '') + '>' +
                        tubularTemplateService.generateFields(scope.columns) +
                        '\r\n<button class="btn btn-primary" ng-click="$parent.save()" ng-disabled="!$parent.model.$valid()">Save</button>' +
                        '\r\n<button class="btn btn-danger" ng-click="$parent.cancel()" formnovalidate>Cancel</button>' +
                        '\r\n</tb-form>';
                };

                me.exportPluker = function(files) {
                    var postData = {};

                    angular.forEach(files, function(file) {
                        postData['files[' + file.name + ']'] = file.content;
                    });

                    postData['tags[0]'] = "angularjs";
                    postData['tags[1]'] = "tubular";
                    postData['tags[1]'] = "autogenerated";
                    postData.private = true;
                    postData.description = "Tubular Sample";

                    formPostData('http://plnkr.co/edit/?p=preview', false, postData);
                };
            }
        ]);
})();